### ISSUE TITLE
활동 보여주기

### ISSUE THREAD

**Issue by pongsoyun** [ParkEunwoo/seoul-smart-api#16]

**Comment by ParkEunwoo** [comment]
신청기간인지
신청마감인지
진행중인 활동인지
 종료된 활동인지
구분했으면 합니다.

**Comment by ParkEunwoo** [comment]
페이지네이션 5개로 구현해주시면 됩니다

**Comment by pongsoyun** [comment]
@ParkEunwoo 
1. 신청기간/마감/진행중/종료된 활동을 `Activity{ status: String }`으로 표현하려고 하는데 워딩 4가지는 `application`, `closed`, `ongoing`, `end` 으로 하려 합니다. 피드백 부탁드립니다!
2. 그리고, 활동이 모두 종료되면 status를 `end`로 변경하는 function이 없는데, todo에 추가해도 괜찮을까요?

**Comment by ParkEunwoo** [comment]
1. Mongoose schema에 보면 상태 4가지에 대한 type이 지정되어있습니다
2. 상태변경에 대한 function은 하나로 충분합니다

**Comment by ParkEunwoo** [comment]
status를 기준으로 쿼리를 여러번 날려서 가져올건지 아니면 sorting만 해도 될지 고민해보았으면 좋겠습니다

**Comment by ParkEunwoo** [comment]
아직 디자이너와 얘기가 안됐지만 만약 저런식으로 status마다 각각 쿼리를 날린다면 앱 화면에서 어떤식으로 동작하게 될까요? 제 생각에는 분리해서 가져온다기보단 아직 모집중인것 부터 완료한 순서로 정렬해서 가져오는 것이 표현하기 쉬울것같은데 어떤가요

**Comment by pongsoyun** [comment]
@ParkEunwoo 좋은의견 감사합니다. 그렇게 정렬해서 모든 값을 가져오는 것이 좋겠네요!
