### ISSUE TITLE
활동등록하기

### ISSUE THREAD

**Issue by pongsoyun** [ParkEunwoo/seoul-smart-api#2]
모임을 개설하는 자가 활동을 등록하는 란이다. 
name, userId, total, date, startTime, progressTime, placeId, roomName, content, type -> return Activity

**Comment by pongsoyun** [comment]
모임을 개설하는 자가 활동을 등록하는 란이다. 
name, userId, total, date, startTime, progressTime, placeId, roomName, content, type -> return Activity

**Comment by ParkEunwoo** [comment]
오탈자 맞습니다 수정했습니다
